### ISSUE TITLE
Tests with Intern/Atom/atom-typescript and Code Completion

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#1]
In this template, when creating unit tests, the proper way to refer to your modules so they get built properly is:

```ts
import myModule = require('src/myModule.ts');
```

But when using Atom and atom-typescript, this module is not found and therefore breaks any code completion/in editor validation when writing your test cases.

**Comment by kitsonk** [comment]
Nevermind... once you properly do a `grunt clean build` the `dts-generator` sorts things out for you.

**Comment by kitsonk** [comment]
Actually it seems to come and go, so I suspect there is a more solid way (or clear instructions) on how to configure/build a package to allow proper code completion.

**Comment by bryanforbes** [comment]
I made some changes yesterday in 469f468b30c08f60758d4b90a37d0cdf62bc0420 which should fix this problem. As you develop, JS emitted from the source in `src` and `tests` will be placed into `_build`. The test tasks in grunt will use the files in `_build`. This should work with grunt and with atom-typescript. Let me know if you still run into problems.
