### ISSUE TITLE
Distribution inconsistancies between dojo-core and package template

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#13]
`dojo/core` outputs a `dist/_typings` directory while `dojo2-package-template` outputs this to `dist/typings`.

**Comment by maier49** [comment]
I think this was fixed by [this commit](https://github.com/dojo/core/commit/90048884b5d48a124aaa064bef398e76a741889d) to `dojo/core` that changed its output directory from `dist/_typings` to `dist/typings`.

**Comment by kitsonk** [comment]
Closed by 90048884b5d48a124aaa064bef398e76a741889d
