### ISSUE TITLE
Update Chai d.ts to v3.

### ISSUE THREAD

**Issue by mwistrand** [dojo/dojo2-package-template#21]
Intern 3.0 uses Chai 3.0, which contains methods and signatures not available in the current 2.0.0 typings.

**Comment by mwistrand** [comment]
[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/chai) contains typings for both v2.0.0 and v3.2.0. Since Intern uses v3.0.0, we can either manually clean up the v3.2.0 typings to remove the changes below, or include the v3.2.0 typings as-is.

Version 3.1 adds:
* `NaN`, `extensible`, `sealed`, and `frozen` properties.
* `isNaN`, `extensible`, `isExtensible`, `notExtensible`, `isNotExtensible`, `sealed`, `notSealed`, `isNotSealed`, `frozen, `isFrozen`, `notFrozen`, and `isNotFrozen` methods.

Version 3.2 swaps aliases/default method names. For example, `isNotFrozen` becomes the main method, and `notFrozen` an alias.

**Comment by dylans** [comment]
Or we could ask @csnover about perhaps updating Intern to use Chai 3.2.0?

**Comment by mwistrand** [comment]
That definitely works, but I was unsure as to whether we would want a temporary update to dojo's d.ts dependencies in the meantime. And for what it's worth, I have a branch locally to update Intern's Chai to the most recent version (3.4.2); I just need to open an issue for it.

**Comment by kitsonk** [comment]
> Or we could ask @csnover about perhaps updating Intern to use Chai 3.2.0?

Or submit a PR that passes all the test, including the updated typings.  Whenever I have submitted an update PR like that, as long as it passes the tests, @csnover merges it.

**Comment by dylans** [comment]
> Or submit a PR that passes all the test, including the updated typings. Whenever I have submitted an update PR like that, as long as it passes the tests, @csnover merges it.

Yes, that's more what I meant. Really I meant to make sure @csnover doesn't have any pressing reason to not update at this time.

**Comment by kitsonk** [comment]
This is being done as part of the realignment of the distributions and the migration to typings/typings
