### ISSUE TITLE
Allow Dojo 2 Packages Testing to run against SauceLabs or BrowserStack

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#22]
Our packaging should allow us to seamlessly test against SauceLabs or BrowserStack.  It should have two separate tests of environments to run against and should be addressable via the grunt tasks.

**Comment by kitsonk** [comment]
Now we just need to port it into the rest of the packages:

- [ ] core
- [ ] loader
- [ ] parser
- [ ] compose
- [ ] dom
- [ ] i18n
- [ ] crypto
- [ ] routing

**Comment by vansimke** [comment]
I've updated all of the targeted platforms to support running test suite against Sauce Labs and Browserstack.
