### ISSUE TITLE
We should leverage `exclude` property in tsconfig.json

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#26]
The `tsconfig.json` now supports the `exclude` property.  We should adapt our builds to utilise that instead of "re-writing" the `tsconfig.json`.

**Comment by kitsonk** [comment]
For information, glob support in `tsconfig.json` looks like it will arrive in [TypeScript 2.0](https://github.com/Microsoft/TypeScript/issues/1927).  So maybe we want to put this on hold until then?

**Comment by vansimke** [comment]
@kitsonk  Can you check this out https://github.com/vansimke/core/tree/issue_26_package_template to see if this is along the lines of what you're thinking? If it is, then I can continue with the removal of filesGlob from the tsconfig file. That is used throughout the Gruntfile, so I want to make sure I'm on the right track before I fully commit to this action.

**Comment by kitsonk** [comment]
Bleugh... it looks like [filesGlob](https://github.com/Microsoft/TypeScript/issues/1927) support is coming in 2.0.  Upon reflection we should just wait and see what 2.0 brings before we go around and redo everything.  I am going to close for now and we can revisit later.
