### ISSUE TITLE
Upgrade to Grunt 1.0.0

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#28]
Grunt 1.0.0 is released.  We should upgrade.

- [ ] Upgrade package template (this repo)
- [x] Changes to dojo/grunt-dojo2?
- [x] dojo/core
- [x] dojo/loader
- [x] dojo/compose
- [ ] dojo/parser
- [ ] dojo/actions
- [ ] dojo/dom
- [ ] dojo/i18n
- [ ] dojo/routing
- [ ] dojo/crypto

**Comment by jdonaghue** [comment]
I have made all of the changes and committed to my forked repos. Just want to test out a little more thoroughly before submitting PR's.

**Comment by kitsonk** [comment]
This has been finished via various updates to packages.
