### ISSUE TITLE
Custom tslint rules

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#35]
There are a few things covered in the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md) that are not caught by the linter.  For example, the alignment of conditional blocks.  For example this is "valid" to tslint:

``` typescript
if (true) {
    console.log('true');
} else {
    console.log('false');
}
```

When in fact, this is what the preferred style is:

``` typescript
if (true) {
    console.log('true');
}
else {
    console.log('false');
}
```

We should investigate how difficult it is to write [custom rules](https://github.com/palantir/tslint#custom-rules) for this and how to integrate them into the packaging.

**Comment by kitsonk** [comment]
References dojo/meta#164

**Comment by dylans** [comment]
Superseded by the switch to use Prettier, #99
