### ISSUE TITLE
Remove IE9 from testing configuration

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#37]
Due to dojo/meta#40 we should remove IE9 from our tests configuration for both SauceLabs and BrowserStack.  We should also make sure each repo has this updated:
- [x] [`dojo/core`](https://github.com/dojo/core/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/loader`](https://github.com/dojo/loader/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/dom`](https://github.com/dojo/dom/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/parser`](https://github.com/dojo/parser/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/compose`](https://github.com/dojo/compose/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/actions`](https://github.com/dojo/actions/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/i18n`](https://github.com/dojo/i18n/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/routing`](https://github.com/dojo/routing/blob/master/tests/intern-saucelabs.ts)
- [ ] [`dojo/crypto`](https://github.com/dojo/crypto/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/widgets`](https://github.com/dojo/widgets/blob/master/tests/intern-saucelabs.ts)
- [x] [`dojo/grunt-dojo2`](https://github.com/dojo/grunt-dojo2/blob/master/tests/intern-saucelabs.ts)

**Comment by agubler** [comment]
All done apart from crypto but that is not currently an active dojo2 module.
