### ISSUE TITLE
Upgrade CI to Node 5.1

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#39]
Travis now supports Node 5.1.  We should migrate our CI to that version.

The biggest challenge will be that npm@3 will no longer install peer dependencies automatically.  Some of the Dojo 2 packages required peer dependencies to build properly.  That means we will have to `npm install` these dependencies as part of the `.travis.yml` file.

The repos we need to address:

* [x] [`dojo/core`](https://github.com/dojo/core)
* [x] [`dojo/loader`](https://github.com/dojo/loader)
* [x] [`dojo/dom`](https://github.com/dojo/dom)
* [ ] [`dojo/parser`](https://github.com/dojo/parser)
* [x] [`dojo/compose`](https://github.com/dojo/compose)
* [x] [`dojo/actions`](https://github.com/dojo/actions)
* [ ] [`dojo/i18n`](https://github.com/dojo/i18n)
* [x] [`dojo/routing`](https://github.com/dojo/routing)
* [ ] [`dojo/crypto`](https://github.com/dojo/crypto)
* [x] [`dojo/widgets`](https://github.com/dojo/widgets)
* [x] [`dojo/grunt-dojo2`](https://github.com/dojo/grunt-dojo2)

**Comment by agubler** [comment]
All the repos have been updated to node 6 in the `.travis.yml` and the remaining repos have PRs raised.
