### ISSUE TITLE
Consider using "files" in package.json rather than .npmignore

### ISSUE THREAD

**Issue by novemberborn** [dojo/dojo2-package-template#42]
`.npmignore` is a blacklist, `files` is a whitelist.

It's hard to maintain a blacklist, e.g. `/html-report` is missing from `.npmignore` currently. Blacklists don't account for any temporary files the publisher may have either.

Given the consistent build output it should be a lot easier to maintain the `files` whitelist.

https://docs.npmjs.com/files/package.json#files

**Comment by kitsonk** [comment]
Sounds like a great idea...
