### ISSUE TITLE
bower.json ignores test, not tests

### ISSUE THREAD

**Issue by kfranqueiro** [dojo/dojo2-package-template#5]
The template's `bower.json` includes `"test"` in `"ignore"`, but our scaffolding includes a `tests` folder, not `test`.

This will need to be fixed in all of our packages so far, too...

* [x] loader
* [x] core
* [x] crypto
* [x] dom
* [x] routing
* [x] i18n

**Comment by mwistrand** [comment]
I also included a PR for the newer [compose](https://github.com/dojo/compose) repo.
