### ISSUE TITLE
.tsconfig*.json

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#55]
Are `.tsconfig*.json` supposed to be checked into repos?  Should they be added to `.gitignore`?

**Comment by agubler** [comment]
They should've be added to the `.gitignore` - I though I did this as I worked through the TS2.0 changes.

Once https://github.com/dojo/grunt-dojo2/pull/30 is in then we won't need to ignore them as it will clean up the `.tsconfig*.json` files

**Comment by agubler** [comment]
This should no longer be an issue, the task now cleans up the temporary files.
