### ISSUE TITLE
Remove node_modules cache from .travis.yml

### ISSUE THREAD

**Issue by kitsonk** [dojo/dojo2-package-template#75]
We have had too many issues with `node_modules` being stale in a cache and not installing what would be installed with a clean install for CI.  This means we sometimes get false positives and negatives.

**Comment by agubler** [comment]
This needs to be done for all our dojo2 packages also

- [ ] [dojo-has](https://github.com/dojo/has)
- [ ] [dojo-shim](https://github.com/dojo/shim)
- [ ] [dojo-core](https://github.com/dojo/core)
- [ ] [dojo-compose](https://github.com/dojo/compose)
- [ ] [dojo-widgets](https://github.com/dojo/widgets)
- [ ] [dojo-actions](https://github.com/dojo/actions)
- [ ] [dojo-routing](https://github.com/dojo/routing)
- [ ] [dojo-cli](https://github.com/dojo/cli)
- [ ] [dojo-cli-build](https://github.com/dojo/cli-build)
- [ ] [dojo-cli-create-app](https://github.com/dojo/cli-create-app)
- [ ] [dojo-loader](https://github.com/dojo/loader)
- [ ] [dojo-dom](https://github.com/dojo/dom)
- [ ] [dojo-examples](https://github.com/dojo/examples)
- [ ] [dojo-interfaces](https://github.com/dojo/interfaces)
- [ ] [dojo-stores](https://github.com/dojo/stores)
- [ ] [dojo-i18n](https://github.com/dojo/i18n)
- [ ] [dojo-cli-css-typings](https://github.com/dojo/cli-css-typings)
