### ISSUE TITLE
LICENSE date should just be 2015

### ISSUE THREAD

**Issue by kfranqueiro** [dojo/dojo2-package-template#8]
The LICENSE currently says 2004-2015.  I assume this should actually just be 2015, assuming it was accidental copypasta from Dojo 1, but is my assumption correct?

We will need to update this in all repositories created to date:

* [x] loader
* [x] core
* [x] crypto
* [x] dom
* [x] routing
* [x] i18n

**Comment by mwistrand** [comment]
I've opened PRs with this change for the above repos, as well as for [dojo/parser](https://github.com/dojo/parser).
